config/routes.rb
Rails.application.routes.draw do
  resources :images, path: 'i'

  resources :lessons, path: 'l', only: [] do
    resources :slides, path: 's'
    resources :feedbacks, path: 'f'
  end

  resources :courses, path: 'c' do
    resources :lessons, path: 'l'
  end

  match(
    'slides/execute_ruby' => 'slides#execute_ruby',
    as: 'execute_ruby', via: :post
  )

  root to: 'courses#index'
end

app/models/slide.rb
class Slide < ApplicationRecord
  # Validations
  validates :title, :lesson, presence: true
  validates :title, :extra_classes, :style, length: { maximum: 255 }
  validates :number, presence: true
  validates :number, allow_nil: true, allow_blank: true,
    numericality: { greater_than: 0, only_integer: true }
  validates :number, allow_nil: true, allow_blank: true,
    uniqueness: { scope: :lesson_id }

  # Relations
  belongs_to :lesson, touch: true
  has_many :nodes, -> { order rank: :asc }, dependent: :destroy
  has_many :code_nodes, -> { order rank: :asc }
  has_many :text_nodes, -> { order rank: :asc }

  accepts_nested_attributes_for :nodes, allow_destroy: true

  def all_nodes
    (code_nodes | text_nodes).sort
  end

  def anchor
    "slide-#{number}"
  end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :require_local, except: [:index, :show]
  before_action :load_lesson

  layout ->(controller) { controller.request.xhr? ? false : 'application' }

  # GET /lessons/1/slides
  # GET /lessons/1/slides.json
  def index
    @title = t('view.slides.index_title')
    @slides = @lesson.slides.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render json: @slides }
    end
  end

  # GET /lessons/1/slides/1
  # GET /lessons/1/slides/1.json
  def show
    @title = t('view.slides.show_title')
    @slide = @lesson.slides.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render json: @slide }
    end
  end

  # GET /lessons/1/slides/new
  # GET /lessons/1/slides/new.json
  def new
    @title = t('view.slides.new_title')
    @slide = @lesson.slides.build

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render json: @slide }
    end
  end

  # GET /lessons/1/slides/1/edit
  def edit
    @title = t('view.slides.edit_title')
    @slide = @lesson.slides.find(params[:id])
  end

  # POST /lessons/1/slides
  # POST /lessons/1/slides.json
  def create
    @title = t('view.slides.new_title')
    @slide = @lesson.slides.build slide_params

    respond_to do |format|
      if @slide.save
        format.html { redirect_to(course_lesson_url(@lesson.course, @lesson, anchor: @slide.anchor), notice: t('view.slides.correctly_created')) }
        format.json  { render json: @slide, status: :created, location: @slide }
      else
        format.html { render action: 'new' }
        format.json  { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1/slides/1
  # PUT /lessons/1/slides/1.json
  def update
    @title = t('view.slides.edit_title')
    @slide = @lesson.slides.find(params[:id])

    respond_to do |format|
      if @slide.update slide_params
        format.html { redirect_to(course_lesson_url(@lesson.course, @lesson, anchor: @slide.anchor), notice: t('view.slides.correctly_updated')) }
        format.json  { head :ok }
      else
        format.html { render action: 'edit' }
        format.json  { render json: @slide.errors, status: :unprocessable_entity }
      end
    end

  rescue ActiveRecord::StaleObjectError
    redirect_to edit_lesson_slide_url(@lesson, @slide), alert: t('view.slides.stale_object_error')
  end

  # DELETE /lessons/1/slides/1
  # DELETE /lessons/1/slides/1.json
  def destroy
    @slide = @lesson.slides.find(params[:id])
    @slide.destroy

    respond_to do |format|
      format.html { redirect_to(lesson_slides_url(@lesson)) }
      format.json  { head :ok }
    end
  end

  # POST /lessons/1/slides/execute_ruby
  def execute_ruby
    code = <<-RUBY
      begin
        $stdout = StringIO.new
        #{params[:code_node][:code]}
        $stdout.string
      ensure
        $stdout = STDOUT
      end
    RUBY

    @out = ROOT_BINDING.eval(code)
  end

  private

  def load_lesson
    @lesson = Lesson.find(params[:lesson_id]) if params[:lesson_id]
  end

  def slide_params
    params.require(:slide).permit(
      :title, :number, :extra_classes, :style, :lock_version,
      nodes_attributes: [:id, :type, :content, :lang, :rank, :lock_version]
    )
  end
end

app/helpers/slides_helper.rb
module SlidesHelper
  def show_options_for_code_node(form)
    langs = CodeNode::LANGS.map { |l| [t("view.slides.langs.#{l}"), l] }

    form.input :lang, label: false, collection: langs, prompt: true
  end

  def draw_node_optionals(node)
    if node.kind_of?(CodeNode)
      case node.lang
      when 'ruby'
        out = link_to(
          t('view.slides.switch_code_view'), '#',
          data: { 'toggle-edition' => true },
          class: [
            'edit-code', 'btn', 'btn-xs', 'btn-default', node.css_class
          ].compact.join(' ')
        )

        out << render(
          partial: 'slides/execute_ruby',
          locals: { node: node }
        )

        raw(out) if local?
      when 'html'
        out = link_to(
          t('view.slides.show_html'), '#',
          data: { 'show-html' => true },
          class: [
            'edit-code', 'btn', 'btn-xs', 'btn-default', node.css_class
          ].compact.join(' ')
        )
        content = content_tag :div, raw(node.content)

        out << content_tag(:textarea, raw(content), class: 'html-code hidden')

        unless @modal_html_displayed
          @modal_html_displayed = true

          content_for :content_bottom do
            render partial: 'slides/modal_for_result', locals: {
              id: 'modal-html'
            }
          end
        end

        raw(out)
      when 'java_script'
        out = link_to(
          t('view.slides.execute'), '#',
          data: { 'execute-js' => true },
          class: [
            'edit-code', 'btn', 'btn-xs', 'btn-default', node.css_class
          ].compact.join(' ')
        )

        out << content_tag(
          :textarea, raw(node.content), class: 'js-code hidden'
        )

        raw(out)
      end
    end
  end
end

app/views/slides/_execute_ruby.html.erb
<div class="code-form" style="display: none;">
  <div class="row">
    <div class="col-md-12">
      <%= simple_form_for :code_node, url: execute_ruby_path, html: { class: 'ruby-code' }, remote: true do |f| %>
        <div class="field">
          <%= f.input(
            :code, as: :text, label: false,
            input_html: { value: node.content, id: "code_#{node.id}", class: 'col-md-12', rows: 6 }
          ) %>
        </div>

        <div class="actions">
          <%= f.button :submit, t('view.slides.execute'), class: 'btn-default avoid-disable' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% unless @modal_code_displayed %>
  <% @modal_code_displayed = true %>

  <%= content_for :content_bottom do %>
    <%= render partial: 'slides/modal_for_result', locals: { id: 'modal-code' } %>
  <% end %>
<% end %>

app/views/slides/_form.html.erb
<%= simple_form_for([@lesson, @slide]) do |f| %>
  <%= content_for :js_extra do -%>
    <%= raw "var textNode='#{generate_template(f, :nodes,
      locals: { disabled: false }, object: TextNode.new)}';" %>
    <%= raw "var codeNode='#{generate_template(f, :nodes,
      locals: { disabled: false }, object: CodeNode.new)}';" %>
  <% end -%>

  <div class="row">
    <div class="col-md-6">
      <%= f.input :title, input_html: { autofocus: true, maxlength: 255 } %>
      <%= f.input :number, input_html: { min: 1, max: 999, autocomplete: 'off' } %>
    </div>
    <div class="col-md-6">
      <%= f.input :extra_classes, input_html: { maxlength: 255 } %>
      <%= f.input :style, input_html: { maxlength: 255 } %>
    </div>
  </div>

  <div class="page-header">
    <h3><%= t 'view.slides.nodes' %></h3>
  </div>

  <div class="row">
    <div class="col-md-8">
      <h4><%= Node.human_attribute_name 'content' %></h4>
    </div>
    <div class="col-md-2">
      <h4><%= Node.human_attribute_name 'options' %></h4>
    </div>
  </div>

  <div id="nodes" class="items">
    <%= f.simple_fields_for :nodes do |n_f| %>
      <%= render partial: 'node', locals: {
        f: n_f, is_dynamic: false
      } %>
    <% end %>
  </div>

  <div>
    <%= link_to(
      t('view.slides.add_text_node'), '#',
      class: 'btn btn-default btn-xs', data: {
        template: 'textNode', container: '#nodes', event: 'addNestedItem'
      }
    ) %> |
    <%= link_to(
      t('view.slides.add_code_node'), '#',
      class: 'btn btn-default btn-xs', data: {
        template: 'codeNode', container: '#nodes', event: 'addNestedItem'
      }
    ) %>
  </div>

  <br />

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
    <div class="pull-right"><%= yield :form_actions %></div>
  </div>
<% end %>
<script type="text/javascript">Util.refreshSortNumbers();</script>

app/views/slides/_modal_for_result.html.erb
<div class="modal fade" id="<%= id %>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3><%= t('view.slides.execution_results_title') %></h3>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-default" data-dismiss="modal"><%= t('label.close') %></a>
      </div>
    </div>
  </div>
</div>

app/views/slides/_node.html.erb
<% id = dynamic_object_id('node', f) %>
<% hide = is_dynamic || f.object.marked_for_destruction? %>
<div class="node nested-item row" id="<%= id %>" <%= raw 'style="display: none;"' if hide %>>
  <div class="col-md-8">
    <%= f.input :content, label: false, input_html: { rows: 4 } %>
  </div>
  <div class="col-md-2">
    <% if f.object.kind_of?(CodeNode) %>
      <%= show_options_for_code_node(f) %><br />
    <% end %>
    <%= f.input :css_class, label: false, input_html: { placeholder: t('view.slides.css_class') } %>
  </div>
  <div class="col-md-2">
    <%= link_to_remove_nested_item(f, 'node') %>
    <%= f.input :rank, as: :hidden, input_html: { class: :sort_number } %>
    <%= f.input :type, as: :hidden %>
    <%= f.input :lock_version, as: :hidden %>
  </div>
</div>
<% if is_dynamic %>
  <script type="text/javascript">
    Helper.show('#<%= id %>', function() {
      $('textarea[name$="[content]"]', $('#<%= id %>')).focus();
    });

    Util.refreshSortNumbers();
  </script>
<% end -%>

app/views/slides/_slide.html.erb
<% cache [slide, has_not_voted?, local?] do %>
  <section class="slide <%= raw slide.extra_classes %>" id="<%= slide.anchor %>" style="<%= raw slide.style %>">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-header">
        <div class="navbar-brand"><%= slide.title %></div>
      </div>
      <div class="navbar-right">
        <span class="badge"><%= slide.number %></span>
      </div>
    </div>

    <div class="content">
      <% slide.all_nodes.each do |node| %>
        <div class="node">
          <%= draw_node_optionals(node) %>
          <%= node.draw %>
        </div>
      <% end %>
      <% if last %>
        <% if has_not_voted? %>
          <div class="row">
            <div class="col-md-4">&nbsp;</div>
            <div class="col-md-4">
              <%= render template: 'feedbacks/new' %>
            </div>
          </div>
        <% elsif !local? %>
          <div class="feedback"><%= render template: 'feedbacks/show' %></div>
        <% end %>
      <% end %>
    </div>
    <footer class="alert alert-info">
      <%= t('app.powered_by.html') %>
      <div class="btn-group dropup pull-right">
        <%= link_to('#', class: 'btn btn-xs dropdown-toggle', data: { toggle: 'dropdown' }) do %>
          <span class="glyphicon glyphicon-cog"></span>
        <% end %>

        <ul class="dropdown-menu">
          <% if local? %>
            <li>
              <%= link_to t('view.slides.new'), new_lesson_slide_path(lesson), data: { action: 'new' } %>
            </li>
            <li>
              <%= link_to t('label.edit'), edit_lesson_slide_path(lesson, slide), data: { action: 'edit' } %>
            </li>
          <% end %>
          <li><%= link_to t('label.list'), lesson_slides_path(lesson) %></li>
          <li>
            <%= link_to(
              t('view.slides.increase_font_size'), '#',
              data: { 'increase-font-size' => true, 'target' => '.slide' }
            ) %>
          </li>
          <li>
            <%= link_to(
              t('view.slides.decrease_font_size'), '#',
              data: { 'decrease-font-size' => true, 'target' => '.slide' }
            ) %>
          </li>
        </ul>
      </div>
      <time class="pull-right badge"><%= Time.now.to_s(:time) %></time>
    </footer>
  </section>
<% end %>

app/views/slides/edit.html.erb
<%= content_for :form_actions do %>
  <%= link_to_show course_lesson_path(@lesson.course, @lesson, anchor: @slide.anchor) %> |
  <%= link_to t('label.list'), lesson_slides_path(@lesson) %>
<% end %>

<%= render 'form' %>

app/views/slides/execute_ruby.js.erb
$('#modal-code .modal-body').html($('<pre></pre>').text('<%= j @out %>'));
$('#modal-code').modal('show');

app/views/slides/index.html.erb
<table class="table table-striped">
  <caption>
    <h3><%= @lesson %></h3>
  </caption>

  <thead>
    <tr>
      <th><%= Slide.human_attribute_name 'title' %></th>
      <th><%= Slide.human_attribute_name 'number' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slides.each do |slide| %>
      <tr>
        <td><%= slide.title %></td>
        <td><%= slide.number %></td>
        <td><%= link_to_show course_lesson_path(@lesson.course, @lesson, anchor: slide.anchor) %></td>
        <td><%= link_to_edit edit_lesson_slide_path(@lesson, slide) %></td>
        <td><%= link_to_destroy lesson_slide_path(@lesson, slide) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= pagination_links(@slides) %>

<nav class="form-actions">
<%= link_to t('view.slides.new'), new_lesson_slide_path(@lesson), class: 'btn btn-primary' %>
</nav>

app/views/slides/new.html.erb
<%= content_for :form_actions do %>
  <%= link_to t('label.list'), lesson_slides_path(@lesson) %>
<% end %>

<%= render 'form' %>

app/views/slides/show.html.erb
<%= render @slide, lesson: @lesson, last: false %>