config/routes.rb
Rails.application.routes.draw do
  resources :images, path: 'i'

  resources :lessons, path: 'l', only: [] do
    resources :slides, path: 's'
    resources :feedbacks, path: 'f'
  end

  resources :courses, path: 'c' do
    resources :lessons, path: 'l'
  end

  match(
    'slides/execute_ruby' => 'slides#execute_ruby',
    as: 'execute_ruby', via: :post
  )

  root to: 'courses#index'
end

app/views/shared/_alert.html.erb
<footer class="alert alert-error fade in" data-dismiss="alert" data-close-after="10000">
  <a class="close">&times;</a>
  <strong><%= flash.alert %></strong>
</footer>

app/views/shared/_menu.html.erb
<div class="navbar navbar-default navbar-fixed-top hidden-print" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to t('app.name'), root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= content_tag(
          :li, link_to(t('menu.courses'), courses_path),
          class: ('active' if controller_name == 'courses')
        ) %>
        <%= content_tag(
          :li, link_to(t('menu.images'), images_path),
          class: ('active' if controller_name == 'images')
        ) %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_notice.html.erb
<footer class="alert alert-info fade in" data-dismiss="alert" data-close-after="10000">
  <a class="close">&times;</a>
  <strong><%= flash.notice %></strong>
</footer>