config/routes.rb
Rails.application.routes.draw do
  resources :images, path: 'i'

  resources :lessons, path: 'l', only: [] do
    resources :slides, path: 's'
    resources :feedbacks, path: 'f'
  end

  resources :courses, path: 'c' do
    resources :lessons, path: 'l'
  end

  match(
    'slides/execute_ruby' => 'slides#execute_ruby',
    as: 'execute_ruby', via: :post
  )

  root to: 'courses#index'
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  LOCALHOST = ['127.0.0.1', '::1']

  default_scope -> { order created_at: :asc }
  scope :remote, -> { where.not ip: LOCALHOST }
  scope :local, -> { where ip: LOCALHOST }

  # Callbacks
  before_destroy :check_if_can_be_destroyed

  # Validations
  validates :rate, presence: true, inclusion: { in: 1..5 }
  validates :ip, presence: true, uniqueness: { scope: :lesson_id }

  # Relations
  belongs_to :lesson

  def can_be_destroyed?
    LOCALHOST.include?(self.ip)
  end

  private

    def check_if_can_be_destroyed
      throw :abort unless can_be_destroyed?
    end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :require_local, only: [:index, :edit, :update, :destroy]
  before_action :load_lesson

  layout ->(controller) { controller.request.xhr? ? false : 'application' }

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @title = t('view.feedbacks.index_title')
    @feedbacks = @lesson.feedbacks.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @title = t('view.feedbacks.show_title')
    @feedback = find_feedback

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @title = t('view.feedbacks.new_title')
    @feedback = @lesson.feedbacks.build(default_args)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @title = t('view.feedbacks.edit_title')
    @feedback = find_feedback
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @title = t('view.feedbacks.new_title')
    @feedback = @lesson.feedbacks.build default_args.reverse_merge(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to [@lesson, @feedback], notice: t('view.feedbacks.correctly_created') }
        format.json { render json: @feedback, status: :created, location: @feedback }
      else
        format.html { render action: 'new' }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @title = t('view.feedbacks.edit_title')
    @feedback = find_feedback

    respond_to do |format|
      if @feedback.update default_args.reverse_merge(feedback_params)
        format.html { redirect_to [@lesson, @feedback], notice: t('view.feedbacks.correctly_updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1.json
  def destroy
    @feedback = find_feedback
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to lesson_feedbacks_url(@lesson) }
      format.json { head :ok }
    end
  end

  private

    def default_args
      { ip: request.remote_ip }
    end

    def find_feedback
      local? ?
        @lesson.feedbacks.find(params[:id]) :
        @lesson.feedbacks.find_by_id_and_ip(params[:id], request.remote_ip)
    end

    def load_lesson
      @lesson = Lesson.find(params[:lesson_id]) if params[:lesson_id]
    end

    def feedback_params
      params.require(:feedback).permit(:comments, :rate, :ip, :lesson_id)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= simple_form_for([@lesson, @feedback], defaults: { input_html: { class: 'col-md-6' } }) do |f| %>
  <%= f.input :rate, input_html: { autofocus: true, min:1, max: 5 } %>
  <%= f.input :ip, input_html: { maxlength: 255 } %>
  <%= f.input :comments, input_html: { rows: 4 } %>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
    <div class="pull-right"><%= yield :form_actions %></div>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<%= content_for :form_actions do %>
  <%= link_to_show lesson_feedback_path(@lesson, @feedback, details: true) %> |
  <%= link_to t('label.list'), lesson_feedbacks_path(@lesson) %>
<% end %>

<%= render 'form' %>

app/views/feedbacks/index.html.erb
<table class="table table-striped">
  <caption>
    <h4><%= link_to @lesson, [@lesson.course, @lesson]%></h4>
  </caption>
  <thead>
    <tr>
      <th><%= Feedback.human_attribute_name 'rate' %></th>
      <th><%= Feedback.human_attribute_name 'ip' %></th>
      <th><%= Feedback.human_attribute_name 'comments' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.rate %></td>
        <td><%= feedback.ip %></td>
        <td><%= feedback.comments %></td>
        <td><%= link_to_show lesson_feedback_path(@lesson, feedback, details: true) %></td>
        <td><%= link_to_edit edit_lesson_feedback_path(@lesson, feedback) %></td>
        <td><%= link_to_destroy [@lesson, feedback] if feedback.can_be_destroyed? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= pagination_links(@feedbacks) %>

<nav class="form-actions">
  <%= link_to t('label.back'), course_lessons_path(@lesson.course) %>
</nav>

app/views/feedbacks/new.html.erb
<div class="feedback">
  <%= simple_form_for([@lesson, @feedback], remote: true) do |f| %>
    <div class="rating">
      <% (1..5).reverse_each do |i| %>
        <%= f.radio_button :rate, i.to_s, id: "star#{i}" %>
        <%= f.label(
          :rate, nil,
          for: "star#{i}", class: "for-#{i}-stars glyphicon glyphicon-star",
          title: t("view.feedbacks.rate.#{i}")
        ) %>
      <% end %>
    </div>

    <%= f.input :comments, label: false, input_html: {
      rows: 3, class: 'col-md-12',
      placeholder: Feedback.human_attribute_name('comments')
    } %>

    <div class="actions">
      <%= f.button :submit, class: 'btn-default btn-lg' %>
    </div>
  <% end %>
</div>

app/views/feedbacks/show.html.erb
<% if params[:details] %>
  <div class="page-header">
    <h1><%= @feedback.lesson %></h1>
  </div>

  <div>
    <strong><%= Feedback.human_attribute_name 'rate' %></strong>:
    <%= @feedback.rate %>
  </div>

  <br />

  <div>
    <strong><%= Feedback.human_attribute_name 'ip' %></strong>:
    <%= @feedback.ip %>
  </div>

  <br />

  <div>
    <strong><%= Feedback.human_attribute_name 'comments' %></strong>:
    <%= simple_format @feedback.comments %>
  </div>

  <nav class="form-actions">
    <%= link_to_edit edit_lesson_feedback_path(@lesson, @feedback) %> |
    <% if @feedback.can_be_destroyed? %>
      <%= link_to_destroy [@lesson, @feedback] %> |
    <% end %>
    <%= link_to t('label.back'), lesson_feedbacks_path(@lesson) %>
  </nav>
<% else %>
  <div class="alert alert-success">
    <button class="close" data-dismiss="alert">&times;</button>
    <p><%= t('view.feedbacks.vote.html') %></p>
  </div>
<% end %>